### ISSUE TITLE
html is rendered with markup inside <pre><code> tags

### ISSUE THREAD

**Issue by nbarrett** [macedigital/angular-markdown-it#5]
I've configured my angular app using [the default instructions](https://github.com/macedigital/angular-markdown-it#getting-started) but the resultant html is enclosed within `<pre><code>` tags:

![image](https://user-images.githubusercontent.com/626941/31057495-ae45c45e-a6db-11e7-9660-b9373c1a845b.png)

I must be doing something wrong - can you enlighten me please? I'm using angular 1.6.

**Comment by macedigital** [comment]
@nbarrett Sorry, I didn't answer earlier.

I'm pretty sure this is caused by indentation of the input data. Markdown treats lines with an indentation of 4 spaces as [code-blocks](https://daringfireball.net/projects/markdown/syntax#precode).

I made a demo page a while back at https://macedigital.github.io/angular-markdown-it/. Output looks fine to me, see screenshot from demo-page:

![screenshot from 2017-12-07 16-41-13](https://user-images.githubusercontent.com/248495/33723695-9b61ab3e-db6d-11e7-9be1-e64cb21ed96a.png)

Let me know if you still have that issue.

**Comment by nbarrett** [comment]
Thanks very much! I eventually worked this out after finding exactly the same behaviour on another markdown project then worked out the error of my ways 😬
